"""Committed card tables: one JSON file per set under `data/cards/`, generated by
`arena-wizard sync-cards` and reviewed in a pull request.

Serialization is deterministic (sorted cards, sorted keys, no timestamps, LF endings), so
syncing twice against unchanged Scryfall data rewrites identical bytes and a real change
shows up as a readable diff.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any

from arena_wizard.domain.cards import Card, CardFace, Color, Rarity
from arena_wizard.domain.sets import EventType

FORMAT_VERSION = 1
CARD_TABLE_DIR = Path(__file__).resolve().parent / "data" / "cards"


@dataclass(frozen=True, slots=True)
class HeaderInfo:
    """The card names from a 17Lands game-file header, used to prove coverage."""

    event_type: EventType
    names: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class CardTable:
    """Every Arena printing a pool of one set can contain."""

    set_code: str
    scryfall_queries: tuple[str, ...]
    header: HeaderInfo | None
    cards: tuple[Card, ...]


def collector_sort_key(number: str) -> tuple[int, str]:
    """Sort collector numbers numerically, then by suffix: 9 < 10 < 158 < 158a < 158b."""
    suffix = number.lstrip("0123456789")
    digits = number[: len(number) - len(suffix)]
    return (int(digits) if digits else -1, suffix)


def card_sort_key(card: Card) -> tuple[str, tuple[int, str], str]:
    """Order cards by set, collector number, then Scryfall id."""
    return (card.set_code, collector_sort_key(card.collector_number), card.scryfall_id)


def unresolved_names(table: CardTable) -> tuple[str, ...]:
    """Return header names that match no card's front name or full name, in header order.

    Args:
        table: The table to check.

    Returns:
        Names 17Lands records that the table cannot resolve; empty when it is complete
        or has no header yet.
    """
    if table.header is None:
        return ()
    known = {card.front_name for card in table.cards} | {card.name for card in table.cards}
    return tuple(name for name in table.header.names if name not in known)


def _card_to_json(card: Card) -> dict[str, Any]:
    """Convert a card to plain JSON types."""
    return {
        "scryfall_id": card.scryfall_id,
        "oracle_id": card.oracle_id,
        "arena_id": card.arena_id,
        "name": card.name,
        "front_name": card.front_name,
        "layout": card.layout,
        "set_code": card.set_code,
        "collector_number": card.collector_number,
        "rarity": card.rarity.value,
        "mana_cost": card.mana_cost,
        "mana_value": card.mana_value,
        "type_line": card.type_line,
        "oracle_text": card.oracle_text,
        "power": card.power,
        "toughness": card.toughness,
        "colors": [c.value for c in card.colors],
        "color_identity": [c.value for c in card.color_identity],
        "produced_mana": list(card.produced_mana),
        "faces": [
            {
                "name": f.name,
                "mana_cost": f.mana_cost,
                "type_line": f.type_line,
                "oracle_text": f.oracle_text,
                "power": f.power,
                "toughness": f.toughness,
            }
            for f in card.faces
        ],
        "image_uri": card.image_uri,
        "artist": card.artist,
        "released_at": card.released_at,
    }


def _card_from_json(raw: dict[str, Any]) -> Card:
    """Rebuild a card from its JSON form."""
    return Card(
        scryfall_id=raw["scryfall_id"],
        oracle_id=raw["oracle_id"],
        arena_id=raw["arena_id"],
        name=raw["name"],
        front_name=raw["front_name"],
        layout=raw["layout"],
        set_code=raw["set_code"],
        collector_number=raw["collector_number"],
        rarity=Rarity(raw["rarity"]),
        mana_cost=raw["mana_cost"],
        mana_value=raw["mana_value"],
        type_line=raw["type_line"],
        oracle_text=raw["oracle_text"],
        power=raw["power"],
        toughness=raw["toughness"],
        colors=tuple(Color(c) for c in raw["colors"]),
        color_identity=tuple(Color(c) for c in raw["color_identity"]),
        produced_mana=tuple(raw["produced_mana"]),
        faces=tuple(CardFace(**face) for face in raw["faces"]),
        image_uri=raw["image_uri"],
        artist=raw["artist"],
        released_at=raw["released_at"],
    )


def table_to_json(table: CardTable) -> str:
    """Serialize a table deterministically. Pure.

    Args:
        table: The table to serialize.

    Returns:
        UTF-8-ready JSON text ending in a newline.
    """
    header = (
        None
        if table.header is None
        else {"event_type": table.header.event_type.value, "names": list(table.header.names)}
    )
    document = {
        "format_version": FORMAT_VERSION,
        "set_code": table.set_code,
        "scryfall_queries": list(table.scryfall_queries),
        "seventeenlands_header": header,
        "card_count": len(table.cards),
        "cards": [_card_to_json(card) for card in sorted(table.cards, key=card_sort_key)],
    }
    return json.dumps(document, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def table_from_json(text: str) -> CardTable:
    """Parse a table serialized by `table_to_json`.

    Args:
        text: The JSON text.

    Returns:
        The table.

    Raises:
        ValueError: The document has a format version this code does not read.
    """
    document = json.loads(text)
    if document.get("format_version") != FORMAT_VERSION:
        raise ValueError(f"unsupported card table format: {document.get('format_version')!r}")
    raw_header = document["seventeenlands_header"]
    header = (
        None
        if raw_header is None
        else HeaderInfo(EventType(raw_header["event_type"]), tuple(raw_header["names"]))
    )
    return CardTable(
        set_code=document["set_code"],
        scryfall_queries=tuple(document["scryfall_queries"]),
        header=header,
        cards=tuple(_card_from_json(card) for card in document["cards"]),
    )


def write_card_table(table: CardTable, path: Path) -> bool:
    """Write a table as UTF-8 with LF endings, only when its content changed.

    Args:
        table: The table to write.
        path: The destination file.

    Returns:
        True when the file was created or changed; False when it already matched.
    """
    text = table_to_json(table)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def load_packaged_card_table(set_code: str) -> CardTable:
    """Load a committed card table from the installed package.

    Args:
        set_code: The set code, e.g. "SOS". Case-insensitive.

    Returns:
        The table.

    Raises:
        FileNotFoundError: No table is packaged for the set.
    """
    path = resources.files("arena_wizard").joinpath("data", "cards", f"{set_code.upper()}.json")
    if not path.is_file():
        raise FileNotFoundError(f"no card table packaged for '{set_code}'")
    return table_from_json(path.read_text(encoding="utf-8"))
