"""Per-set configuration: release dates, card sources, pool-size range, and data sources.

Adding a set is configuration, not code: a YAML file under `config/sets/` plus a card
table generated by `arena-wizard sync-cards`. Every date window uses the Arena release
date, because roughly half of the 17Lands games for a set are played before the paper
release (measured on SOS and HOB, 2026-09-28).
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from importlib import resources
from typing import Any

import yaml

EMBARGO_DAYS = 11
"""17Lands asks third-party tools not to present a new set's data until its 12th day on
Arena, so the embargo lifts at the start of release day plus eleven days."""


class Format(StrEnum):
    """A product format a player enters. Distinct from where the statistics come from."""

    BO1_SEALED = "bo1_sealed"
    TRAD_SEALED = "trad_sealed"


class EventType(StrEnum):
    """A 17Lands data stream, named exactly as 17Lands names it."""

    SEALED = "Sealed"
    TRAD_SEALED = "TradSealed"
    PREMIER_DRAFT = "PremierDraft"
    ARENA_DIRECT_SEALED = "ArenaDirect_Sealed"


class ConfigError(ValueError):
    """A set configuration is missing a field or has one of the wrong shape."""


@dataclass(frozen=True, slots=True)
class SetConfig:
    """Everything the app needs to know about one set that is not in the card table."""

    code: str
    name: str
    arena_release_date: dt.date
    paper_release_date: dt.date
    formats: tuple[Format, ...]
    card_set_codes: tuple[str, ...]
    scryfall_queries: tuple[str, ...]
    seventeenlands_expansion: str
    nonbasic_pool_range: tuple[int, int]
    stats_sources: Mapping[Format, tuple[EventType, ...]]
    public_files: tuple[EventType, ...] = ()
    """17Lands public files published for the set. Past the embargo, pastes of the same
    data are refused and ignored (decision 0005, rule 4), even where no copy is cached."""

    @property
    def embargo_until(self) -> dt.date:
        """The first day 17Lands-derived views of this set may be shown."""
        return self.arena_release_date + dt.timedelta(days=EMBARGO_DAYS)


def _require(raw: Mapping[str, Any], key: str) -> Any:
    """Return `raw[key]`, raising a ConfigError that names the key when it is absent."""
    if key not in raw or raw[key] is None:
        raise ConfigError(f"set config is missing required field '{key}'")
    return raw[key]


def _as_date(value: Any, key: str) -> dt.date:
    """Coerce a YAML date or an ISO date string, naming the field on failure."""
    if isinstance(value, dt.date):
        return value
    try:
        return dt.date.fromisoformat(str(value))
    except ValueError as exc:
        raise ConfigError(f"set config field '{key}' is not an ISO date: {value!r}") from exc


def _as_str_tuple(value: Any, key: str) -> tuple[str, ...]:
    """Coerce a non-empty list of strings, naming the field on failure."""
    if not isinstance(value, list) or not value or not all(isinstance(v, str) for v in value):
        raise ConfigError(f"set config field '{key}' must be a non-empty list of strings")
    return tuple(value)


def parse_set_config(raw: Mapping[str, Any]) -> SetConfig:
    """Validate a raw mapping (usually parsed YAML) into a SetConfig.

    Args:
        raw: The mapping to validate.

    Returns:
        The validated configuration.

    Raises:
        ConfigError: A field is missing or malformed; the message names the field.
    """
    pool_range = _require(raw, "nonbasic_pool_range")
    if (
        not isinstance(pool_range, list)
        or len(pool_range) != 2
        or not all(isinstance(v, int) for v in pool_range)
        or pool_range[0] > pool_range[1]
    ):
        raise ConfigError("set config field 'nonbasic_pool_range' must be [low, high] integers")

    raw_sources = _require(raw, "stats_sources")
    if not isinstance(raw_sources, Mapping) or not raw_sources:
        raise ConfigError("set config field 'stats_sources' must be a non-empty mapping")
    try:
        formats = tuple(Format(f) for f in _as_str_tuple(_require(raw, "formats"), "formats"))
        stats_sources = {
            Format(fmt): tuple(EventType(e) for e in _as_str_tuple(events, f"stats_sources.{fmt}"))
            for fmt, events in raw_sources.items()
        }
    except ValueError as exc:
        if isinstance(exc, ConfigError):
            raise
        raise ConfigError(f"set config has an unknown format or event type: {exc}") from exc

    return SetConfig(
        code=str(_require(raw, "code")),
        name=str(_require(raw, "name")),
        arena_release_date=_as_date(_require(raw, "arena_release_date"), "arena_release_date"),
        paper_release_date=_as_date(_require(raw, "paper_release_date"), "paper_release_date"),
        formats=formats,
        card_set_codes=_as_str_tuple(_require(raw, "card_set_codes"), "card_set_codes"),
        scryfall_queries=_as_str_tuple(_require(raw, "scryfall_queries"), "scryfall_queries"),
        seventeenlands_expansion=str(_require(raw, "seventeenlands_expansion")),
        nonbasic_pool_range=(pool_range[0], pool_range[1]),
        stats_sources=stats_sources,
        public_files=_public_files(raw.get("public_files", [])),
    )


def _public_files(raw: Any) -> tuple[EventType, ...]:
    """The optional list of published 17Lands files, as event types; absent means none."""
    if raw in (None, []):
        return ()
    try:
        return tuple(EventType(e) for e in _as_str_tuple(raw, "public_files"))
    except ValueError as exc:
        if isinstance(exc, ConfigError):
            raise
        raise ConfigError(f"set config public_files has an unknown event type: {exc}") from exc


def packaged_set_codes() -> tuple[str, ...]:
    """Return the codes of every set with a packaged configuration, sorted."""
    folder = resources.files("arena_wizard").joinpath("config", "sets")
    return tuple(
        sorted(p.name.removesuffix(".yaml") for p in folder.iterdir() if p.name.endswith(".yaml"))
    )


def load_set_config(code: str) -> SetConfig:
    """Load and validate the packaged configuration for one set.

    Args:
        code: The set code, e.g. "SOS". Case-insensitive.

    Returns:
        The validated configuration.

    Raises:
        ConfigError: No configuration exists for the code, or it is invalid.
    """
    path = resources.files("arena_wizard").joinpath("config", "sets", f"{code.upper()}.yaml")
    if not path.is_file():
        raise ConfigError(f"no set configuration for '{code}'")
    return parse_set_config(yaml.safe_load(path.read_text(encoding="utf-8")))
